### ISSUE TITLE
App times out on search...

### ISSUE THREAD

**Issue by PeterEIER** [denniedegroot/com.apple.itunes#2]
After successful pairing, when I try to search my iTunes library the app gives me a time-out error.

Installed the app via dev tools to do some troubleshooting... the app does communicate with my iTunes lib for sure...

![screen shot 2017-10-14 at 21 09 41](https://user-images.githubusercontent.com/25422313/31578608-c6dd2694-b124-11e7-86a5-2062b0f5b84a.png)

![screen shot 2017-10-14 at 21 15 54](https://user-images.githubusercontent.com/25422313/31578611-e3f7f768-b124-11e7-9aff-22f2a2293831.png)

**Comment by denniedegroot** [comment]
The app in its current state does not support the Homey media feature.

**Comment by kapusticka** [comment]
When you can add support for Athom Homey?

**Comment by denniedegroot** [comment]
Athom stated that media functionality will disappear. So I am closing this ticket.
