### ISSUE TITLE
can play iTunes music with homey

### ISSUE THREAD

**Issue by kingdong78** [denniedegroot/com.apple.itunes#3]
Hi,

first of all thanks for creating a app for homey.

problem:
I can't get homey music to work with iTunes.
Pairing works with homey but when i fill a music search request in homey music.
It gives a fault error ( de app deed er te lang over te reageren) i tried different thing as reinstalling the app but cant get it to work.
Could someone help me out.

regards

hank

**Comment by denniedegroot** [comment]
The app in its current state does not support the Homey media feature.
Also the media feature will disappear from Homey in a future update.
